### ISSUE TITLE
Street lights with multi light:count ignore specified directions

### ISSUE THREAD

**Issue by PeterLeGras** [sb12/OSMStreetLight#14]
In my country it is common to have two bent mast lights connected to the same pole, typically facing away from each other. 

In the following example, the `light:count=2` light masts point roughly east and west, but the default rendering in OSMStreetLight is north and south. Setting the direction using `direction:100;280` does not solve the issue. Perhaps the direction could be taken into account with respect to the axis of rotation of the lamp.

Example:
![image](https://user-images.githubusercontent.com/52308086/94338643-4671da80-0037-11eb-8279-2c47a1ad8d05.png)

Suggestion:
![image](https://user-images.githubusercontent.com/52308086/94338856-f1cf5f00-0038-11eb-8ad9-3cb504c52156.png)

**Comment by sb12** [comment]
This should already be working. Can you please send an OSM link to the street lights in the screenshot. Please also make sure that you use the up-to-date instance on http://osmstreetlight.bplaced.net

**Comment by PeterLeGras** [comment]
Hi, the street light in the ss is: https://www.openstreetmap.org/node/7877192271
There are a few similar ones nearby that I also can't get to work. The tags were added a few days ago.

**Comment by sb12** [comment]
Ok, it has only been working with the `light:direction` key, but not for the `direction` key.
I guess this is also commonly used, therefore I added support for the `direction` key.
Has been solved in 63ddbe9c8d93fd8de692c4ec10d4a70bf3be9937
