### ISSUE TITLE
No lamps are shown with multiple browers

### ISSUE THREAD

**Issue by IeP4nieF** [sb12/OSMStreetLight#20]
The chart is working with my private installation on the desktop (Debian) with firefox and librewolf. But it is not working with chromium and konqueror on my desktop and not working with any browser (tried fennec, FOSS Browser and ungoogled chromium) on android.

With "not working" I mean: chart is shown and slider for darkness works, but no lamps are shown. Also the language switching does not work (language is not switched). The spinning wheel in the upper left does turn red (I think for showing an error).

Is there a possibility for debugging? Can I find some logs somewhere? If so, I can help debugging this bug.

Thanks and best regards

**Comment by mkgrgis** [comment]
Let's check existence of lamps in affected browsers. Now we have alternative: data error or web error. For web error there is alternative sources to: client or server.

**Comment by sb12** [comment]
Thanks for the report. 

> The spinning wheel in the upper left does turn red (I think for showing an error).

This usually means, that there was some error when loading the data from overpass api. These could be caused e.g. by a timeout or a "Too may requests" error. These are more likely when you have an area with a lot of data or have a slow internet connection. 
In chromium, you can use the developer tools to see whether there are any error messages when fetching the data.

I will see if I can further improve the error handling to actually show a meaningful error.

> Also the language switching does not work (language is not switched).

Yes, I can confirm that. Language switching does not work in Android, Chromium or Microsoft Edge for me either. It does work in Firefox on desktop though. I need to investigate that further.

**Comment by IeP4nieF** [comment]
Thanks for the hint "developer console"!

As you can see here

https://anonfiles.com/7fE0V3a3y8/osmlights_debug_png

one loading of overpass-api.de is blocked, because of insecure http instead https. Second there are two 404 messages for pngs.

Hope that it helps. Let me know, if you need to know more.

**Comment by IeP4nieF** [comment]
No messages were written to the developer console, when I use the switch for switching the language...

**Comment by sb12** [comment]
Thanks for the debug information.

Could you please try, if https://github.com/sb12/OSMStreetLight/tree/https solves the Mixed Content Error when requesting data from overpass api via https.

**Comment by IeP4nieF** [comment]
Yes! https://github.com/sb12/OSMStreetLight/tree/https solves the Mixed Content Error with every browser (as mentioned in my first post). Thanks a lot!

FYI: The language switch still only works in firefox and librewolf. But that is not important for me.

**Comment by sb12** [comment]
Thanks for testing. I have opened a new issue for the language switching problem.
