### ISSUE TITLE
light:lamp_type may be double of lamp_type

### ISSUE THREAD

**Issue by mkgrgis** [sb12/OSMStreetLight#21]
See detailed values from https://wiki.openstreetmap.org/wiki/Key:lamp_type and https://taginfo.openstreetmap.org/keys/lamp_type. I think no need for light:lamp_type as specialization of lamp_type. Additional OSM comments see https://www.openstreetmap.org/changeset/116657834
Maybe we can add list of "electrical" values in lamp_type.

**Comment by sb12** [comment]
`light:lamp_type` is currently not supported by this tool, so I do not understand the reason for this bug and the changeset discussion.

You can find the supported tags and values in https://github.com/sb12/OSMStreetLight/blob/master/README.md
