### ISSUE TITLE
Support tower:type=lighting

### ISSUE THREAD

**Issue by mikelortega** [sb12/OSMStreetLight#25]
It would be nice to visualize this kind of lights. These are usually even bigger and brighter than regular street lights.
[https://wiki.openstreetmap.org/wiki/Tag:tower:type%3Dlighting](https://wiki.openstreetmap.org/wiki/Tag:tower:type%3Dlighting)

**Comment by sb12** [comment]
Thanks for your suggestion. It's now added and shown in the same style as `light_source=floodlight`.
