### ISSUE TITLE
Add links website <-> github

### ISSUE THREAD

**Issue by jidanni** [sb12/OSMStreetLight#27]
1. https://wiki.openstreetmap.org/wiki/Osmstreetlight says
2. https://github.com/sb12/OSMStreetLight/ is related to
2. http://osmstreetlight.bplaced.net/

but there are no such clues on 2) and 3).

**Comment by sb12** [comment]
The links are there in the [README.md](https://github.com/sb12/OSMStreetLight/blob/master/README.md) and the [About](http://osmstreetlight.bplaced.net/about.html) page. They might need an English translation though...
