### ISSUE TITLE
Add 'view my location' button

### ISSUE THREAD

**Issue by jidanni** [sb12/OSMStreetLight#30]
So we can fly to the streetlights nearby.

**Comment by sb12** [comment]
I have added an optional "view my location" button in the code. Unfortunately, I had to disable it on the demo page as most browsers deny geolocation for sites without SSL certificates (see #32). 

Nevertheless the map will now try to find a rough location based on the IP address on startup, so at least there is a bit less moving around. A searchbar was also added (Requested in #4 for a long time).
