### ISSUE TITLE
Allow HTTPS

### ISSUE THREAD

**Issue by jidanni** [sb12/OSMStreetLight#32]
http://osmstreetlight.bplaced.net/ causes browser warnings. Therefore there should be a
https://osmstreetlight.bplaced.net/ website.

**Comment by sb12** [comment]
http://osmstreetlight.bplaced.net is meant as a demo website only and uses a free webhosting provider which does not support https in the free plan.

**Comment by jidanni** [comment]
Hmmm, I found "5 Best: Free Hosting with SSL Certificate Included (2024)"

**Comment by sb12** [comment]
Well, it was actually easier than I thought. New test installation is on https://sb12.github.io/OSMStreetLight/
