### ISSUE TITLE
Include Utility Pole with Street Lights

### ISSUE THREAD

**Issue by PrasannaVenkadesh** [sb12/OSMStreetLight#34]
It is becoming a very common practice in India to save space and reuse existing pole infrastructure for multiple purpose. For example, mounting a street lamp on existing Power pole. This is also why "Utility Pole" tag is proposed and accepted in OSM.

At present, the light map doesn't render street lights mounted as part of utility pole. Including `node["utility"~"street_lighting"];` will take such utility poles with street lamps into account as well.

For example take a look here. https://overpass-turbo.eu/s/1QTN

Some people may include `"highway=street_lamp"` for Utility Pole and some may find that `"utility="power;street_lighting"` is sufficient. Hence I suggest to include querying for utility to improve coverage.

**Comment by sb12** [comment]
Thanks for your suggestion.

According to the [`man_made=utility_pole` Wiki page](https://wiki.openstreetmap.org/wiki/Tag:man_made%3Dutility_pole) this tag is meant for "a single pole supporting elevation of any of various and unspecified public utilities, such as [...] lighting". 

So, a `man_made=utility_pole` `utility=street_lighting` could just carry a cable for street lamps, but does not need to be a light source itself. Example: [Overpass Turbo](https://overpass-turbo.eu/s/1QUs) [Mapillary](https://www.mapillary.com/app/?lat=49.36863343236&lng=8.1682656426059&z=18.43081532342381&pKey=553997138903232&focus=photo)

I suggest to specify that a pole actually carries a street lamp by adding e.g. `highway=street_lamp` or `light_source=lantern`.

**Comment by PrasannaVenkadesh** [comment]
setting highway=street_lamp tag to utility pole converts it into a street lamp pole ripping off any utility pole properties. That is the reason why I avoided it.
