### ISSUE TITLE
Add darkness slider

### ISSUE THREAD

**Issue by jidanni** [sb12/OSMStreetLight#5]
Add a slider, so one can adjust the darkness of the background.
One can imagine many city governments around the world using your map,
where workers would like to double check the location by having a better look at the base map... or for workers with poor eyesight.

**Comment by sb12** [comment]
Thank you for your suggestion.
I have added a darkness slider now to the map. [http://osmstreetlight.bplaced.net](http://osmstreetlight.bplaced.net) is already updated.
