### ISSUE TITLE
Fix issues found by Developer Tools' console

### ISSUE THREAD

**Issue by jidanni** [sb12/OSMStreetLight#8]
Using Developer Tools' console, one sees e.g.,

> leaflet.js:5 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

etc. Perhaps correct all of these.

**Comment by sb12** [comment]
As far as I understand these issues are just some information of possibilities for performance improvements and all are due to libraries provided by other parties like leaflet and jsquery.
So there is nothing I can do about it.
